services:
  - type: web
    name: drivesafe
    env: python
    buildCommand: ./build.sh
    startCommand: cd drivesafe && gunicorn web_app:app --bind 0.0.0.0:$PORT --timeout 120
    plan: free
    branch: main
    healthCheckPath: /
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.7
    autoDeploy: true
    previewFeatureFlags:
      - assetsPreserved
