services:
  - type: web
    name: drivesafe
    env: python
    buildCommand: |
      python -m pip install --upgrade pip
      cd drivesafe && pip install -r requirements.txt
      python -c "import cv2; print('OpenCV version:', cv2.__version__)"
    startCommand: cd drivesafe && FLASK_ENV=production gunicorn web.app:app --bind 0.0.0.0:$PORT --timeout 120 --workers 1
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.7
      - key: PYTHONPATH
        value: .
      - key: FLASK_ENV
        value: production
      - key: FLASK_APP
        value: web.app
    healthCheckPath: /
    autoDeploy: true
    previewFeatureFlags:
      - assetsPreserved
